{{- if .Values.pdsAccounts }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-pds-accounts
  labels:
    {{- include "app-template.labels" (dict "context" (index .Subcharts "app-template")) | nindent 4 }}
spec:
  rules:
    {{- range .Values.pdsAccounts }}
    - host: "{{ . }}.{{ $.Values.pdsAccountDomain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-app-template
                port:
                  number: 3000
    {{- end }}
{{- end }}