forgejo:
  redis-cluster:
    enabled: false
  postgresql:
    enabled: true
    primary:
      persistence:
        enabled: true
        storageClass: nfs-client
      startupProbe:
        enabled: true
  postgresql-ha:
    enabled: false

  strategy:
    type: Recreate

  persistence:
    enabled: true
    storageClass: nfs-client

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: code.cluster.diluz.io
        paths:
          - path: /
            pathType: Prefix

  gitea:
    admin:
      username: "maybeanerd"
      password: "<<CHANGE_ME>>"
      email: "forgejo@diluz.io"
    config:
      database:
        DB_TYPE: postgres
      session:
        PROVIDER: db
      server:
        START_SSH_SERVER: false
      service:
        # Don't allow registration
        DISABLE_REGISTRATION: true
      cache:
        ADAPTER: memory
      queue:
        TYPE: level
      indexer:
        ISSUE_INDEXER_TYPE: bleve
        REPO_INDEXER_ENABLED: true
    # oauth:
    #   - name: "Authentik"
    #     provider: "openidConnect"
    #     key: "<<CHANGE_ME>>"
    #     secret: "<<CHANGE_ME>>"
    #     autoDiscoverUrl: "https://auth.cluster.diluz.io/application/o/forgejo/.well-known/openid-configuration"
