apiVersion: v1
kind: Secret
metadata:
  name: hetzner-s3-backup-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.backups.s3.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backups.s3.secretKey | quote }}
  AWS_ENDPOINTS: {{ .Values.backups.s3.endpoint | quote }}
  VIRTUAL_HOSTED_STYLE: "true"
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-s3
  namespace: {{ .Release.Namespace }}
spec:
  task: backup
  name: daily-s3
  # 3 AM every day
  cron: "0 3 * * *"
  concurrency: 1
  retain: 14
  groups:
    - default
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-system-backup
  namespace: {{ .Release.Namespace }}
spec:
  task: "system-backup"
  # 4 AM, after volume backups
  cron: "0 4 * * *"
  concurrency: 1
  retain: 7
  parameters:
    volumeBackupPolicy: "disabled"
