#!/bin/bash

INTEGRATION_RUNNER_NAME=${INTEGRATION_RUNNER_NAME:-integration-runner}
HELM_POD_RELEASE_LABEL=${HELM_POD_RELEASE_LABEL:-release=$INTEGRATION_RUNNER_NAME}

helm uninstall --timeout=2m --wait "$INTEGRATION_RUNNER_NAME"