{{- define "immich.proxy.hardcodedValues" -}}
global:
  nameOverride: proxy

service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: true
        port: 8080
        protocol: HTTP
{{- end }}

{{ if .Values.proxy.enabled }}
{{- $ctx := deepCopy . -}}
{{- $_ := get .Values "proxy" | mergeOverwrite $ctx.Values -}}
{{- $_ = include "immich.proxy.hardcodedValues" . | fromYaml | merge $ctx.Values -}}
{{- include "bjw-s.common.loader.all" $ctx }}
{{ end }}