{{- define "immich.web.hardcodedValues" -}}
global:
  nameOverride: web

service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: true
        port: 3000
        protocol: HTTP

command: "/bin/sh"
args:
  - "./entrypoint.sh"
{{- end }}

{{ if .Values.web.enabled }}
{{- $ctx := deepCopy . -}}
{{- $_ := get .Values "web" | mergeOverwrite $ctx.Values -}}
{{- $_ = include "immich.web.hardcodedValues" . | fromYaml | merge $ctx.Values -}}
{{- include "bjw-s.common.loader.all" $ctx }}
{{ end }}