---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.6.0/charts/other/app-template/values.schema.json

replicaCount: 1

controllers:
  main:
    strategy: Recreate
    pod:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker

    containers:
      main:
        image:
          # -- image repository
          repository: roundcube/roundcubemail
          # -- image tag
          tag: 1.6.10-fpm
          # -- image pull policy
          pullPolicy: IfNotPresent

        # -- environment variables.
        env:
          - name: ROUNDCUBEMAIL_DEFAULT_HOST
            value: "tls://imap.servivum.com"
          - name: ROUNDCUBEMAIL_DEFAULT_PORT
            value: "993"
          - name: ROUNDCUBEMAIL_SMTP_SERVER
            value: "tls://smtp.servivum.com"
          - name: ROUNDCUBEMAIL_SMTP_PORT
            value: "587"
          - name: ROUNDCUBEMAIL_USERNAME_DOMAIN
            value: "diluz.io"
          - name: ROUNDCUBEMAIL_DB_TYPE
            value: "pgsql"
          - name: ROUNDCUBEMAIL_DB_HOST
            value: "roundcube-postgresql"
          - name: ROUNDCUBEMAIL_DB_PORT
            value: "5432"
          - name: ROUNDCUBEMAIL_DB_NAME
            value: "roundcube"
          - name: ROUNDCUBEMAIL_DB_USER
            value: "roundcube_user"
          - name: ROUNDCUBEMAIL_DB_PASSWORD
            value: "TODOREPLACEME"

        resources:
          # limits:
          #   cpu: 100m
          #   memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi

# -- Configures service settings for the chart.
service:
  main:
    controller: main
    ports:
      http:
        port: 80

# -- Configure persistence settings for the chart under this key.
# persistence:
# For multi replicas to share temp files
#  temp:
#    type: persistentVolumeClaim
#    accessMode: ReadWriteMany
#    storageClass: "nfs-client"
#    size: 1Gi
#    globalMounts:
#      - path: /tmp/roundcube-temp

postgresql:
  enabled: true
  auth:
    username: roundcube_user
    password: "TODOREPLACEME"
    database: roundcube
  primary:
    persistence:
      enabled: true
      storageClass: nfs-client
      accessMode: ReadWriteOnce
      size: 10Gi
    startupProbe:
      enabled: true
      # Give DB time to revive itself from interruption ; Default is 15
      failureThreshold: 256
    containerSecurityContext:
      readOnlyRootFilesystem: false
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: kubernetes.io/role
                  operator: In
                  values:
                    - worker
