kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "data-authentik-postgresql-longhorn"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "longhorn"
  labels:
    recurring-job-group.longhorn.io/default: "true"
    recurring-job-group.longhorn.io/hetzner: "true"
    recurring-job-group.longhorn.io/crmbs: "true"
  resources:
    requests:
      storage: "20Gi"
