---
apiVersion: v2
description: Paperless - Index and archive all of your scanned paper documents
name: paperless
version: 0.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - paperless
icon: https://avatars.githubusercontent.com/u/47271576?s=200&v=4
sources:
  - https://github.com/paperless-ngx/paperless-ngx
maintainers:
  - name: sebastian
    email: sebastian@diluz.io
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
  - name: postgresql
    version: 13.2.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.3.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
