apiVersion: v2
name: paperless
description: "A community-supported supercharged version of paperless: scan, index and archive all your physical documents"
icon: https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/b948750/src-ui/src/assets/logo-notext.svg
type: application
version: 0.1.26
# renovate datasource=docker depName=ghcr.io/paperless-ngx/paperless-ngx
appVersion: 2.5.0
kubeVersion: ">=1.22.0-0"
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.6.0
  - name: postgresql
    version: 15.5.23
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 20.1.1
    condition: redis.enabled
sources:
  - https://github.com/paperless-ngx/paperless-ngx
maintainers:
  - name: sebastian
    email: sebastian@diluz.io
