#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/paperless-ngx/paperless-ngx
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  # @default -- chart.appVersion
  tag: 2.0.0

# -- See the following files for additional environment variables:
# https://github.com/paperless-ngx/paperless-ngx/tree/main/docker/compose/
# https://github.com/paperless-ngx/paperless-ngx/blob/main/paperless.conf.example
# @default -- See below
env:
  # -- Project name
  COMPOSE_PROJECT_NAME: paperless
  # -- Redis to use
  # PAPERLESS_REDIS:
  # -- OCR languages to install
  PAPERLESS_OCR_LANGUAGE: eng
  # USERMAP_UID: 1000
  # USERMAP_GID: 1000
  PAPERLESS_TIME_ZONE: Europe/Berlin
  # -- Database host to use
  # PAPERLESS_DBHOST:
  # -- Port to use
  PAPERLESS_PORT: 8000
  # -- Username for the root user
  PAPERLESS_ADMIN_USER: basti
  # -- Password for the root user
  # PAPERLESS_ADMIN_PASSWORD: admin
  # PAPERLESS_URL: <set to main ingress by default>

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: paperless.cluster.diluz.io
        paths:
          - path: /
            pathType: Prefix

persistence:
  # -- Configure persistence for data.
  # @default -- See values.yaml
  data:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: nfs-client
    mountPath: /usr/src/paperless/data
    emptyDir:
      enabled: false
  # -- Configure persistence for media.
  # @default -- See values.yaml
  media:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: nfs-client
    mountPath: /usr/src/paperless/media
    emptyDir:
      enabled: false
  # -- Configure volume to monitor for new documents.
  # @default -- See values.yaml
  consume:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: nfs-client
    mountPath: /usr/src/paperless/consume
    emptyDir:
      enabled: false
  # -- Configure export volume.
  # @default -- See values.yaml
  export:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: nfs-client
    mountPath: /usr/src/paperless/export
    emptyDir:
      enabled: false

# -- Enable and configure postgresql database subchart under this key.
#    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
# @default -- See values.yaml
postgresql:
  enabled: true
  postgresqlUsername: paperless
  postgresqlPassword: paperless
  postgresqlDatabase: paperless
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: nfs-client

# -- Enable and configure redis subchart under this key.
#    For more options see [redis chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/redis)
# @default -- See values.yaml
redis:
  enabled: true
  auth:
    enabled: false
