## This chart relies on the common library chart from bjw-s
## You can find it at https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
## Refer there for more detail about the supported values

controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: ghcr.io/paperless-ngx/paperless-ngx
          # -- image tag
          tag: 2.8.1
          # -- image pull policy
          pullPolicy: IfNotPresent

        # -- environment variables.
        env:
          # -- Set the container timezone
          PAPERLESS_TIME_ZONE: CET
          PAPERLESS_SECRET_KEY: <REPLACE_ME>
          PAPERLESS_URL: https://paperless.cluster.diluz.io
          PAPERLESS_TIKA_ENABLED: 1
          PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
          PAPERLESS_TIKA_ENDPOINT: http://tika:9998
        # -- Set the resource requests / limits for the container.
        resources:
          # limits:
          #   cpu: 100m
          #   memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
  gotenberg:
    containers:
      main:
        image:
          # -- image repository
          repository: gotenberg/gotenberg
          # -- image tag
          tag: 8.5.0
          # -- image pull policy
          pullPolicy: IfNotPresent

        # The gotenberg chromium route is used to convert .eml files. We do not
        # want to allow external content like tracking pixels or even javascript.
        command:
          - "gotenberg"
          - "--chromium-disable-javascript=true"
          - "--chromium-allow-list=file:///tmp/.*"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
  tika:
    containers:
      main:
        image:
          # -- image repository
          repository: ghcr.io/paperless-ngx/tika
          # -- image tag
          tag: 2.9.1-minimal
          # -- image pull policy
          pullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi

# -- Configures service settings for the chart.
service:
  main:
    ports:
      http:
        port: 8000
  gotenberg:
    controller: gotenberg
    ports:
      http:
        port: 3000
  tika:
    controller: tika
    ports:
      http:
        port: 9998

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: true
    hosts:
      - host: paperless.cluster.diluz.io
        paths:
          - path: /
            pathType: Prefix
            service:
              name: main
              port: http

persistence:
  # -- Configure data volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  data:
    enabled: false
    retain: true
    mountPath: /usr/src/paperless/data
    storageClass: nfs-client
    accessMode: ReadWriteOnce
    size: 1Ti
  # -- Configure media volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  media:
    enabled: false
    retain: true
    mountPath: /usr/src/paperless/media
    storageClass: nfs-client
    accessMode: ReadWriteOnce
    size: 1Ti
  # -- Configure export volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  export:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/export
    storageClass: nfs-client
    accessMode: ReadWriteOnce
    size: 1Gi
  # -- Configure consume volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  consume:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/consume
    storageClass: nfs-client
    accessMode: ReadWriteOnce
    size: 10Gi

# -- Enable and configure postgresql database subchart under this key.
#    If enabled, the app's db envs will be set for you.
#    [[ref]](https://github.com/bitnami/charts/tree/main/bitnami/postgresql)
# @default -- See [values.yaml](./values.yaml)
postgresql:
  enabled: true
  auth:
    database: paperless
    postgresPassword: <REPLACE_ME>
  primary:
    persistence:
      enabled: true
      storageClass: nfs-client
      accessMode: ReadWriteOnce
      size: 10Gi

# -- Enable and configure redis subchart under this key.
#    If enabled, the app's Redis env will be set for you.
#    [[ref]](https://github.com/bitnami/charts/tree/main/bitnami/redis)
# @default -- See [values.yaml](./values.yaml)
redis:
  enabled: true
  auth:
    enabled: true
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 0
