#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml
#

image:
  # -- Image repository
  repository: ghcr.io/paperless-ngx/paperless-ngx
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image tag
  tag: 2.5.0

# -- Environment variables [[ref]](https://docs.paperless-ngx.com/configuration/)
# @default -- See [values.yaml](./values.yaml)
env:
  # -- Set the container timezone
  TZ: CET
  PAPERLESS_SECRET_KEY: <REPLACE_ME>

service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    ports:
      http:
        port: 8000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: paperless.cluster.diluz.io
        paths:
          - path: /
            pathType: Prefix

persistence:
  # -- Configure data volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  data:
    enabled: false
    retain: true
    mountPath: /usr/src/paperless/data
    storageClass: nfs-client
    accessMode: ReadWriteOnce
    size: 1Ti
  # -- Configure media volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  media:
    enabled: false
    retain: true
    mountPath: /usr/src/paperless/media
    storageClass: nfs-client
    accessMode: ReadWriteOnce
    size: 1Ti
  # -- Configure export volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  export:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/export
    storageClass: nfs-client
    accessMode: ReadWriteOnce
    size: 1Gi
  # -- Configure consume volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  consume:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/consume
    storageClass: nfs-client
    accessMode: ReadWriteOnce
    size: 10Gi

# -- Enable and configure postgresql database subchart under this key.
#    If enabled, the app's db envs will be set for you.
#    [[ref]](https://github.com/bitnami/charts/tree/main/bitnami/postgresql)
# @default -- See [values.yaml](./values.yaml)
postgresql:
  enabled: true
  auth:
    database: paperless
    postgresPassword: <REPLACE_ME>
  primary:
    persistence:
      enabled: true
      storageClass: nfs-client
      accessMode: ReadWriteOnce
      size: 10Gi

# -- Enable and configure redis subchart under this key.
#    If enabled, the app's Redis env will be set for you.
#    [[ref]](https://github.com/bitnami/charts/tree/main/bitnami/redis)
# @default -- See [values.yaml](./values.yaml)
redis:
  enabled: true
  auth:
    enabled: true
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 0
