services:
  mage:
    image: ghcr.io/maybeanerd/mage:1.4.54V2-rc.1
    ports:
      - '17171:17171'
      - '17179:17179'
    extra_hosts:
      - 'mage.diluz.io:0.0.0.0'
    environment:
      - MAGE_SERVER_ADDRESS=mage.diluz.io
      - MAGE_SERVER_NAME=mage.diluz.io
      - MAGE_MAX_SECONDS_IDLE=6000
      - MAGE_AUTHENTICATION_ACTIVATED=false
    volumes:
      - xmage-db:/xmage/db
      - xmage-saved:/xmage/saved
volumes:
  xmage-db:
  xmage-saved:
