{{- if and (.Values.persistence.data.enabled) (not .Values.persistence.data.existingClaim) (.Values.persistence.data.isPvc) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "plex.dataPvcName" . }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
  {{- with .Values.persistence.data.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.data.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  {{- end -}}
{{- end -}}
