apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: plex
      protocol: TCP
      name: plex
    {{- with .Values.additionalServicePorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "plex.selectorLabels" . | nindent 4 }}
