apiVersion: v2
name: plex
description: Plex Media Server Helm chart
type: application
version: 0.1.0
home: https://www.plex.tv
keywords:
  - plex
  - media-server
  - plex-media-server
  - streaming
  - tv
icon: https://utkuozdemir.org/helm-charts/plex.png