---
apiVersion: v2
description: Plex Media Server
name: plex
version: 0.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - plex
  - plex-media-server
icon: https://www.plex.tv/wp-content/uploads/2018/01/pmp-icon-1.png
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
maintainers:
  - name: sebastian
    email: sebastian@diluz.io
