#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: docker.io/linuxserver/plex
  # @default -- chart.appVersion
  tag: "1.32.6"
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [plex docs](https://support.plex.tv/articles/201105343-advanced-hidden-server-settings/) for more details.
# **NOTE:** Plex preference options are camelCase and CASE SENSITIVE!
# You can do horrible things to your Plex configuration if you are not careful
# @default -- See below
env:
  # -- Set the container timezone
  TZ: CET
  # ADVERTISE_IP:
  # ALLOWED_NETWORKS:
  # PLEX_CLAIM:
  # PLEX_PREFERENCE_1: "FriendlyName=plex-kubernetes"
  # PLEX_PREFERENCE_2: "EnableIPv6=0"
  # PLEX_PREFERENCE_3: "logDebug=1"
  # PLEX_PREFERENCE_4: "DisableTLSv1_0=1"
  # PLEX_PREFERENCE_5: "LanNetworksBandwidth=xxx.xxx.xxx.0/18\,xxx.xxx.xxx.0/24\,xxx.xxx.xxx.0/24"
  # PLEX_PREFERENCE_6: "TranscoderQuality=2"
  # PLEX_PREFERENCE_7: "TreatWanIpAsLocal=0"
  # PLEX_PREFERENCE_8: "TranscoderH264BackgroundPreset=fast"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    primary: true
    ports:
      http:
        port: 32400

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: plex.cluster.diluz.io
        paths:
          - path: /
            pathType: Prefix

# -- Enable devices to be discoverable
hostNetwork: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: /config
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: nfs-client

  data:
    enabled: true
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: nfs-client

# -- Configure the Security Context for the Pod
podSecurityContext:
  {}
  # runAsUser: 568
  # runAsGroup: 568
  # fsGroup: 568
  # # Hardware acceleration using an Intel iGPU w/ QuickSync
  # # These IDs below should be matched to your `video` and `render` group on the host
  # # To obtain those IDs run the following grep statement on the host:
  # # $ cat /etc/group | grep "video\|render"
  # # video:x:44:
  # # render:x:109:
  # supplementalGroups:
  # - 44
  # - 109

# -- Configure the resource requests and/or limits for the Pod
resources:
  requests:
    #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
    #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
    #   gpu.intel.com/i915: 1
    cpu: 400m
    memory: 512Mi
  # limits:
  #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
  #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
  #   gpu.intel.com/i915: 1
  #   memory: 4096Mi
