---
apiVersion: v2
name: knot
description: knot (AT Protocol Git Server)
type: application
version: 0.1.0
maintainers:
  - name: sebastian
    email: sebastian@diluz.io
dependencies:
  - name: app-template
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.1
