---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.6.0/charts/other/app-template/values.schema.json

controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/advplyr/audiobookshelf
          tag: 2.26.2
          pullPolicy: IfNotPresent
        env: []
        resources:
          requests:
            cpu: 100m
            memory: 128Mi

service:
  main:
    controller: main
    ports:
      http:
        port: 80

serviceAccount:
  create: true

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: "nfs-client"
    accessMode: ReadWriteOnce
    size: 1Gi
  metadata:
    enabled: true
    type: persistentVolumeClaim
    storageClass: "nfs-client"
    accessMode: ReadWriteOnce
    size: 1Gi
  audiobooks:
    enabled: true
    type: persistentVolumeClaim
    storageClass: "nfs-client"
    accessMode: ReadWriteOnce
    size: 1Gi
  podcasts:
    enabled: true
    type: persistentVolumeClaim
    storageClass: "nfs-client"
    accessMode: ReadWriteOnce
    size: 1Gi
