---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.6.0/charts/other/app-template/values.schema.json

controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/advplyr/audiobookshelf
          tag: 2.33.0
          pullPolicy: IfNotPresent
        env: []
        resources:
          requests:
            cpu: 100m
            memory: 128Mi

service:
  main:
    controller: main
    ports:
      http:
        port: 80

serviceAccount:
  create: true

persistence:
  config-longhorn:
    enabled: true
    globalMounts:
      - path: /config
    type: persistentVolumeClaim
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 1Gi
  metadata-longhorn:
    enabled: true
    globalMounts:
      - path: /metadata
    type: persistentVolumeClaim
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 5Gi
  audiobooks-longhorn:
    enabled: true
    globalMounts:
      - path: /audiobooks
    type: persistentVolumeClaim
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 300Gi
  podcasts-longhorn:
    enabled: true
    globalMounts:
      - path: /podcasts
    type: persistentVolumeClaim
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 200Gi

ingress:
  main:
    hosts:
      - host: audiobookshelf.cluster.diluz.io
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
