immich:
  persistence:
    external:
      storageClass: nfs-client
      size: 1Ti
    library:
      storageClass: nfs-client
      size: 1Ti
    machine-learning-cache:
      storageClass: nfs-client
      size: 10Gi

  service:
    server:
      enabled: true
      primary: true
      controller: server
      type: ClusterIP
      ports:
        http:
          enabled: true
          primary: true
          port: 2283
          protocol: HTTP
        metrics-api:
          enabled: false
          port: 8081
          protocol: HTTP
        metrics-ms:
          enabled: false
          port: 8082
          protocol: HTTP

  defaultPodOptions:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: kubernetes.io/role
                  operator: In
                  values:
                    - worker

  postgresql:
    primary:
      persistence:
        storageClass: nfs-client
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
