immich:
  persistence:
    external:
      storageClass: nfs-client
      size: 1Ti
    library:
      storageClass: nfs-client
      size: 1Ti
    machine-learning-cache:
      storageClass: nfs-client
      size: 10Gi

  controllers:
    server:
      containers:
        main:
          env:
            # TODO replace with immich.config once we know the values to put there
            IMMICH_CONFIG_FILE: null

  defaultPodOptions:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: kubernetes.io/role
                  operator: In
                  values:
                    - worker

  postgresql:
    primary:
      persistence:
        storageClass: nfs-client
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
