immich:
  persistence:
    external:
      storageClass: nfs-client
      size: 1Ti
    library:
      storageClass: nfs-client
      size: 1Ti
    machine-learning-cache:
      storageClass: nfs-client
      size: 10Gi

  defaultPodOptions:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: kubernetes.io/role
                  operator: In
                  values:
                    - worker

  postgresql:
    global:
      postgresql:
        auth:
          password: TODOCHANGEME
    primary:
      persistence:
        storageClass: nfs-client
        size: 1Gi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
