---
apiVersion: v2
description: A chart to deploy Maybe Finance on Kubernetes
name: maybe-finance
version: 0.1.4
home: https://github.com/maybe-finance/maybe
sources:
  - https://github.com/maybe-finance/maybe
maintainers:
  - name: sebastian
    email: sebastian@diluz.io
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.6.0
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 16.5.2
