apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix.fullname" . }}-homeserver
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
type: Opaque
stringData:
  homeserver.yaml: |-
    # Generated homeserver configuration
    server_name: "{{ .Values.controllers.main.containers.main.env.SYNAPSE_SERVER_NAME }}"
    pid_file: /data/homeserver.pid
    listeners:
      - port: 8008
        type: http
        tls: false
        resources:
          names: [client]
        x_forwarded: true
    database:
      name: psycopg2
      args:
        user: "postgres"
        password: "{{ .Values.postgresql.auth.password }}"
        database: "postgres"
        host: "{{ include "matrix.fullname" . }}-postgresql"
        port: 5432
    redis:
      enabled: true
      host: "{{ include "matrix.fullname" . }}-redis-master"
      port: 6379
      password: "{{ .Values.redis.auth.password }}"
    # Federation settings (recommended defaults)
    federation_domain_whitelist:
      - "*"
    email:
      smtp_host: smtp.servivum.com
      smtp_port: 587
      require_auth: true
      username: "noreply@diluzio.dev"
      password: "TODO_CHANGE_ME"
    # Security/limits
    rc_message: 1000
    rc_room: 100
