apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix.fullname" . }}-secret
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Bitnami PostgreSQL exposes credentials via templates: use .Release.Name-postgresql for host
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  POSTGRES_DB: postgres
  # Redis URL for synapse
  REDIS_URL: "redis://:{{ .Values.redis.auth.password }}@{{ include "matrix.fullname" . }}-redis-master:6379/0"
