---
{{- $asToken := .Values.whatsappbridge.extraValues.asToken }}
{{- $hsToken := .Values.whatsappbridge.extraValues.hsToken }}
{{- $pickleKey := .Values.whatsappbridge.extraValues.pickleKey }}

apiVersion: v1
kind: Secret
metadata:
  name: "whatsappbridge-secrets"
type: Opaque
data:
  as_token: {{ $asToken | b64enc }}
  hs_token: {{ $hsToken | b64enc }}
  pickle_key: {{ $pickleKey | b64enc }}
  registration.yaml: {{ mergeOverwrite (dict
   "as_token" $asToken
   "hs_token" $hsToken
  ) .Values.whatsappbridge.extraValues.registration | toYaml | b64enc }}
