---
{{- $asToken := get .Values.extraValues.asToken }}
{{- $hsToken := get .VValues.extraValues.hsToken }}

apiVersion: v1
kind: Secret
metadata:
  name: "matrix-whatsapp-bridge-secrets"
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
type: Opaque
data:
  as_token: {{ $asToken | b64enc }}
  hs_token: {{ $hsToken | b64enc }}
  registration.yaml: {{ mergeOverwrite (dict
   "as_token" $asToken
   "hs_token" $hsToken
  ) .Values.extraValues.registration | toYaml | b64enc }}
