secrets:
  serverToken: "TODO REPLACE ME ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64"

app-template:
  controllers:
    attic:
      type: deployment
      replicas: 1
      pod:
        annotations:
          checksum/config: '{{ .Files.Get `server.toml` | sha256sum }}'
      containers:
        app:
          image:
            repository: ghcr.io/zhaofengli/attic
            tag: "latest"
            # sha256:18574aba70fc89d2b695273fbe2e7b2f8ad7e8e786b4cc535124fbe14bada1d0
            # TODO find good way to pin this, as it has no semver releases
          args:
            - --config
            - /etc/attic/server.toml

          ports:
            - name: http
              containerPort: 8080

          env:
            - name: ATTIC_SERVER_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: attic-db-app
                  key: uri
            - name: ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64
              valueFrom:
                secretKeyRef:
                  name: attic-secrets
                  key: ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64

          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  httpHeaders:
                    - name: Host
                      value: attic.cluster.diluz.io
                initialDelaySeconds: 10
                periodSeconds: 30
                timeoutSeconds: 10
                failureThreshold: 3
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  httpHeaders:
                    - name: Host
                      value: attic.cluster.diluz.io
                periodSeconds: 15
                timeoutSeconds: 5
            startup:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  httpHeaders:
                    - name: Host
                      value: attic.cluster.diluz.io
                periodSeconds: 5
                failureThreshold: 30

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 3000m
              memory: 4Gi

  service:
    app:
      controller: attic
      ports:
        http:
          port: 8080
          targetPort: http

  ingress:
    app:
      hosts:
        - host: "attic.cluster.diluz.io"
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: app
                port: http

  persistence:
    server-config:
      type: configMap
      name: attic-config
      globalMounts:
        - path: /etc/attic/server.toml
          subPath: server.toml
          readOnly: true

    blob-storage:
      type: persistentVolumeClaim
      storageClass: "longhorn"
      accessMode: ReadWriteOnce
      size: "100Gi"
      globalMounts:
        - path: /storage

postgres:
  nameOverride: db
  cluster:
    instances: 1
    storage:
      size: "10Gi"
      storageClass: "longhorn"
