---
apiVersion: v2
description: A chart to power 5e tools running on kubernetes
name: 5e-tools
version: 0.1.0
maintainers:
  - name: sebastian
    email: sebastian@diluz.io
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.6.0
