---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.6.0/charts/other/app-template/values.schema.json

controllers:
  main:
    strategy: Recreate
    pod:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
    containers:
      main:
        image:
          # -- image repository
          repository: ghcr.io/5etools-mirror-3/5etools-src
          # -- image tag
          tag: 2.7.0
          # -- image pull policy
          pullPolicy: IfNotPresent
        # -- environment variables.
        # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
        env: []
        resources:
          # limits:
          #   cpu: 100m
          #   memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi

# -- Configures service settings for the chart.
service:
  main:
    controller: main
    ports:
      http:
        port: 80
