---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.1.0/charts/other/app-template/values.schema.json

controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          # -- image repository
          repository: ghcr.io/5etools-mirror-3/5etools-src
          # -- image tag
          tag: 2.5.10
          # -- image pull policy
          pullPolicy: IfNotPresent

        # -- environment variables.
        # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
        env: []
        resources:
          # limits:
          #   cpu: 100m
          #   memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi

# -- Configures service settings for the chart.
service:
  main:
    controller: main
    ports:
      http:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    hosts:
      - host: 5etools.cluster.diluz.io
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
