services:
  dyndns:
    image: davd/docker-ddns:1.5.0
    ports:
      - 53:53
      - 53:53/udp
      - 8080:8080
    environment:
      - SHARED_SECRET=${SHARED_SECRET}
      - ZONE=cluster.diluz.io
      - RECORD_TTL=300
    restart: always
    volumes:
      - dyndns-cache:/var/cache/bind
volumes:
  dyndns-cache:
