{{- if .Values.persistence.data.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "firefish.fullname" . }}-files
  labels:
    {{- include "firefish.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode | quote }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
  {{- end }}
