apiVersion: v1
kind: Secret
metadata:
  name: {{ template "firefish.fullname" . }}-config
  labels:
    {{- include "firefish.labels" . | nindent 4 }}
type: Opaque
data:
  default.yml: {{ include "firefish.configDir.default.yml" . | b64enc }}
