# yaml-language-server: $schema=values.schema.json

matrix-stack:
  # Global server name for Matrix federation
  serverName: 'cluster.diluz.io'

  # Synapse homeserver configuration
  synapse:
    enabled: true
    ingress:
      host: 'matrix.cluster.diluz.io'
    media:
      storage:
        size: 100Gi
        storageClassName: longhorn
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        memory: 4Gi
    nodeSelector:
      kubernetes.io/role: worker

    # Define configs for bridges
    additional:
      whatsappbridge:
        config: |
          app_service_config_files:
            - /data/registrations/whatsapp-registration.yaml
      experimental-features.yaml:
        config: |
          experimental_features:
            msc3202_transaction_extensions: true
            msc2409_to_device_messages_enabled: true
    extraVolumes:
      - name: whatsapp-registration
        secret:
          secretName: whatsappbridge-secrets
    extraVolumeMounts:
      - name: whatsapp-registration
        mountPath: /data/registrations/whatsapp-registration.yaml
        subPath: registration.yaml
        readOnly: true

  # Element Web client
  elementWeb:
    enabled: true
    ingress:
      host: 'element.cluster.diluz.io'
    nodeSelector:
      kubernetes.io/role: worker

  # Element Admin interface
  elementAdmin:
    enabled: true
    ingress:
      host: 'admin-matrix.cluster.diluz.io'
    nodeSelector:
      kubernetes.io/role: worker

  # Matrix Authentication Service
  matrixAuthenticationService:
    enabled: true
    ingress:
      host: 'auth-matrix.cluster.diluz.io'
    extraEnv:
      - name: AUTHENTIK_CLIENT_SECRET
        value: 'TODOREPLACEME'
    additional:
      auth.yaml:
        config: |
          passwords:
            # Users will only be able to log in using upstream OIDC providers
            enabled: false
          upstream_oauth2:
            providers:
              - id: 01HFRQFT5QFMJFGF01P7JAV2ME
                human_name: Authentik
                issuer: "https://auth.cluster.diluz.io/application/o/matrix/"
                client_id: "P5QrehyycvxTxhNNmFGmwjCmgAPHYbjcahzhaIj4"
                client_secret: ${AUTHENTIK_CLIENT_SECRET}
                token_endpoint_auth_method: client_secret_basic
                scope: "openid profile email"
                claims_imports:
                  localpart:
                    action: suggest
                    template: "{{ user.preferred_username }}"
                  displayname:
                    action: suggest
                    template: "{{ user.name }}"
                  email:
                    action: require
                    template: "{{ user.email }}"
    nodeSelector:
      kubernetes.io/role: worker

  # Matrix RTC Backend (for Element Call)
  matrixRTC:
    enabled: true
    ingress:
      host: 'rtc-matrix.cluster.diluz.io'
    sfu:
      manualIP: '46.225.62.164'
      useStunToDiscoverPublicIP: false
      additional:
        config.yaml:
          config: |
            turn:
              relay_range_start: 30000
              relay_range_end: 30100
      exposedServices:
        rtcTcp:
          enabled: true
          # These are also the default values, but the schema wants them to be explicitly set
          portType: NodePort
          port: 30881
        rtcMuxedUdp:
          enabled: true
          # These are also the default values, but the schema wants them to be explicitly set
          portType: NodePort
          port: 30882
        turn:
          enabled: true
          # These are also the default values, but the schema wants them to be explicitly set
          portType: NodePort
          port: 31478
      nodeSelector:
        kubernetes.io/role: worker
    nodeSelector:
      kubernetes.io/role: worker

  # Well-known delegation for federation
  wellKnownDelegation:
    enabled: true

  haproxy:
    nodeSelector:
      kubernetes.io/role: worker

  # PostgreSQL database
  postgres:
    enabled: true

    storage:
      size: 20Gi
      storageClassName: longhorn

    resources:
      requests:
        cpu: 1000m
        memory: 1Gi
      limits:
        memory: 2Gi
    nodeSelector:
      kubernetes.io/role: worker

whatsappbridge:
  global:
    fullnameOverride: whatsappbridge

  extraValues:
    asToken: "TODOREPLACEME"
    hsToken: "TODOREPLACEME"
    registration:
      id: whatsapp
      namespaces:
        users:
          - exclusive: true
            regex: '@whatsapp_.*:cluster\.diluz\.io'
        aliases:
          - exclusive: true
            regex: '#whatsapp_.*:cluster\.diluz\.io'
      url: http://whatsappbridge.matrix.svc.cluster.local:29318
      sender_localpart: whatsappbot
      rate_limited: false
      "de.sorunome.msc2409.push_ephemeral": true
      "io.element.msc4190": true
      "org.matrix.msc3202": true

  controllers:
    whatsapp:
      type: statefulset
      containers:
        app:
          image:
            repository: dock.mau.dev/mautrix/whatsapp
            tag: v26.06
          command:
            - /usr/bin/mautrix-whatsapp
            - --no-update
            - -c
            - /data/config.yaml
          env:
            TZ: UTC
            CHOWN: 'false'
            BRIDGE_APPSERVICE__AS_TOKEN:
              secretKeyRef:
                name: whatsappbridge-secrets
                key: as_token
            BRIDGE_APPSERVICE__HS_TOKEN:
              secretKeyRef:
                name: whatsappbridge-secrets
                key: hs_token
            BRIDGE_ENCRYPTION__PICKLE_KEY: 'TODOCHANGEME'
      pod:
        securityContext:
          fsGroup: 1337
          fsGroupChangePolicy: 'OnRootMismatch'

  service:
    whatsapp:
      controller: whatsapp
      ports:
        http:
          port: 29318

  configMaps:
    whatsapp-config:
      enabled: true
      forceRename: whatsapp-config
      data:
        config.yaml: |
          homeserver:
            address: http://matrix-synapse-main.matrix.svc.cluster.local:8008
            domain: cluster.diluz.io
            software: standard

          appservice:
            address: http://whatsappbridge.matrix.svc.cluster.local:29318
            hostname: 0.0.0.0
            port: 29318
            id: whatsapp
            bot:
              username: whatsappbot
            username_template: whatsapp_{{`{{.}}`}}

          database:
            type: sqlite3-fk-wal
            uri: /data/mautrix-whatsapp.db?_txlock=immediate

          bridge:
            permissions:
              "cluster.diluz.io": user
            command_prefix: "!wa"

          encryption:
            allow: true
            default: true
            require: true
            allow_key_sharing: true
            appservice: true
            msc4190: true
            delete_keys:
              delete_outbound_on_ack: true
              delete_prev_on_new_session: true

          network:
            os_name: Mautrix-WhatsApp bridge
            browser_name: unknown

          env_config_prefix: BRIDGE_

          logging:
            min_level: info
            writers:
              - type: stdout
                format: pretty-colored

  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 2Gi
      globalMounts:
        - path: /data
    config:
      enabled: true
      type: configMap
      name: whatsapp-config
      globalMounts:
        - path: /data/config.yaml
          subPath: config.yaml
    registration:
      enabled: true
      type: secret
      name: whatsappbridge-secrets
      globalMounts:
        - path: /data/registration.yaml
          subPath: registration.yaml
