apiVersion: v2
name: firefish
description: A fun, new, open way to experience social media https://joinfirefish.org

maintainers:
  - name: sebastian
    email: sebastian@diluz.io

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.2

dependencies:
#  - name: elasticsearch
#    version: 19.0.1
#    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
#    condition: elasticsearch.enabled
  - name: postgresql
    version: 13.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
