{{- if .Values.enabled }}
{{- range .Values.migrations }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .destPvc | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "pvc-migration.labels" $ | nindent 4 }}
    app.kubernetes.io/component: migration-dest
spec:
  accessModes:
    - {{ default $.Values.defaults.accessMode .accessMode | quote }}
  {{- if or .storageClass $.Values.defaults.storageClass }}
  storageClassName: {{ default $.Values.defaults.storageClass .storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size | quote }}
{{- end }}
{{- end }}
