---
apiVersion: v2
description: A chart to run cloud native postgres
name: cnpg
version: 0.1.2
maintainers:
  - name: sebastian
    email: sebastian@diluz.io
dependencies:
  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts
    version: 0.29.0
