authentik:
  global:
    # To override bitnami images
    security:
      allowInsecureImages: true
    affinity:
      nodeAffinity:
        # -- Default node affinity rules. Either `none`, `soft` or `hard`
        type: soft
        matchExpressions:
          - key: kubernetes.io/role
            operator: In
            values:
              - worker
  authentik:
    secret_key: "PleaseGenerateA50CharKey"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
      enabled: true
    postgresql:
      password: "ThisIsNotASecurePassword"
    email:
      # -- SMTP Server emails are sent from, fully optional
      host: "smtp.servivum.com"
      # -- SMTP server port
      port: 587
      # -- SMTP credentials, when left empty, no authentication will be done
      username: "noreply@diluzio.dev"
      # -- SMTP credentials, when left empty, no authentication will be done
      password: "TODO_EMAIL_PASSWORD"
      # -- Enable either use_tls or use_ssl, they can't be enabled at the same time.
      use_tls: true
      # -- Enable either use_tls or use_ssl, they can't be enabled at the same time.
      use_ssl: false
      # -- Connection timeout
      timeout: 30
      # -- Email from address, can either be in the format "foo@bar.baz" or "authentik <foo@bar.baz>"
      from: "auth.cluster.diluz.io <noreply@diluzio.dev>"
    server:
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
    worker:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi

  server:
    ingress:
      enabled: true
      hosts:
        - auth.cluster.diluz.io

  postgresql:
    enabled: true
    # Overrides since the bitnami images have been removed
    image:
      registry: docker.io
      repository: library/postgres
      tag: "15.17-bookworm"
    auth:
      password: "TODO CHANGEME"
    primary:
      persistence:
        enabled: true
        existingClaim: "data-authentik-postgresql-longhorn"
      startupProbe:
        enabled: true
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
      # From upstream authentik chart, TODO remove once on latest chart version
      args:
        - -c
        - config_file=/bitnami/postgresql/conf/postgresql.conf
        - -c
        - hba_file=/bitnami/postgresql/conf/pg_hba.conf
      configuration: |
        listen_addresses = '*'
        port = '5432'
        wal_level = 'replica'
        fsync = 'on'
        hot_standby = 'on'
        log_connections = 'false'
        log_disconnections = 'false'
        log_hostname = 'false'
        client_min_messages = 'error'
        include_dir = 'conf.d'
      pgHbaConfiguration: |
        host     all             all             0.0.0.0/0               scram-sha-256
        host     all             all             ::/0                    scram-sha-256
        local    all             all                                     scram-sha-256
        host     all             all        127.0.0.1/32                 scram-sha-256
        host     all             all        ::1/128                      scram-sha-256
      extendedConfiguration: |
        max_connections = 500
      extraEnvVars:
        - name: POSTGRES_DB
          value: '{{ (include "postgresql.v1.database" .) }}'
      resourcesPreset: "none"
      containerSecurityContext:
        readOnlyRootFilesystem: true
      extraVolumeMounts:
        - name: postgresql-socket
          mountPath: /var/run/postgresql
      extraVolumes:
        - name: postgresql-socket
          emptyDir: {}

    readReplicas:
      resourcesPreset: "none"
    backup:
      resourcesPreset: "none"
    passwordUpdateJob:
      resourcesPreset: "none"
    volumePermissions:
      resourcesPreset: "none"
      image:
        repository: debian
        tag: 13-slim

  redis:
    enabled: true
    # temporarily override image since old ones were deleted
    image:
      registry: docker.io
      repository: bitnami/redis
      tag: latest
    master:
      persistence:
        enabled: false
