---
apiVersion: v2
description: A chart to power longhorn
name: longhorn
version: 0.1.0
home: https://longhorn.io/
icon: https://longhorn.io/img/logos/longhorn-horizontal-color.png
maintainers:
  - name: sebastian
    email: sebastian@diluz.io
dependencies:
  - name: longhorn
    repository: https://charts.longhorn.io/
    version: v1.9.1
