nextcloud:
  image:
    flavor: "fpm"
  ingress:
    enabled: true
  nextcloud:
    host: "nextcloud.cluster.diluz.io"
    username: maybeanerd
    password: "TODOCHANGEME"
# mail
  # enabled 	Whether to enable/disable email settings 	false
  # fromAddress 	nextcloud mail send from field 	nil
  # domain 	nextcloud mail domain 	nil
  # smtp
     # host 	SMTP hostname 	nil
     # secure 	SMTP connection ssl or empty 	''
     # port 	Optional SMTP port 	nil
     # authtype 	SMTP authentication method 	LOGIN
     # name 	SMTP username, ONLY the part before the domain name. i.e. 'postmaster' NOT 'postmaster@example.com' 	''
     # password
  cronjob:
    enabled: true
  internalDatabase:
    enabled: false
  externalDatabase:
    enabled: true
    type: "postgresql"
    existingSecret:
      enabled: true
      secretName: nextcloud-cluster-app
      hostKey: host
      usernameKey: username
      passwordKey: password
      databaseKey: dbname
  persistence:
    enabled: true
    storageClass: longhorn
    size: 10Gi
    nextcloudData:
      enabled: true
      storageClass: longhorn
      size: 100Gi
  startupProbe:
    enabled: true
  nginx:
    # To handle e.g. port 80 for healthchecks
    enabled: true

cluster:
  cluster:
    # TODO figure out if 2 is the minimum when wanting easy updates etc
    instances: 1
    storage:
      size: "10Gi"
      storageClass: "longhorn"
    walStorage:
      enabled: true
      size: "1Gi"
      storageClass:	"longhorn"
