immich:
  immich:
    configuration:
      image:
        preview:
          format: webp
        fullsize:
          enabled: true
          format: webp
          quality: 80
      library:
        scan:
          cronExpression: "0 4 * * *"
      machineLearning:
        availabilityChecks:
          enabled: true
          interval: 30000
          timeout: 2000
      metadata:
        faces:
          import: true
      nightlyTasks:
        clusterNewFaces: true
        databaseCleanup: true
        generateMemories: true
        missingThumbnails: true
        startTime: "03:00"
        syncQuotaUsage: true
      notifications:
        smtp:
          enabled: true
          from: "Immich <noreply@diluzio.dev>"
          replyTo: ""
          transport:
            host: "smtp.servivum.com"
            ignoreCert: false
            password: "TODOCHANGEME"
            port: 587
            username: "noreply@diluzio.dev"
      oauth:
        enabled: true
        autoLaunch: true
        autoRegister: true
        buttonText: "Login with Authentik"
        clientId: "x93MIUTyE80epWJKx2ie5yIqqxR2ODPD6aV2vwIS"
        defaultStorageQuota: 10
        issuerUrl: "https://auth.cluster.diluz.io/application/o/immich/"
        timeout: 30000
      passwordLogin:
        enabled: false
      server:
        externalDomain: "https://immich.cluster.diluz.io"
        loginPageMessage: ""
        # not in default at all
        publicUsers: true
      storageTemplate:
        enabled: true
    database:
      storageType: hdd

  persistence:
    external:
      storageClass: nfs-client
      size: 1Ti
      accessMode: ReadWriteOnce
    library:
      existingClaim: data-immich-library-longhorn
    machine-learning-cache:
      storageClass: longhorn
      size: 20Gi
      accessMode: ReadWriteOnce
  defaultPodOptions:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: kubernetes.io/role
                  operator: In
                  values:
                    - worker

  ingress:
    server:
      enabled: true
      hosts:
        - host: immich.cluster.diluz.io
          paths:
            - path: /
              pathType: Prefix

  postgresql:
    auth:
      password: TODOCHANGEME
    primary:
      persistence:
        enabled: true
        existingClaim: "data-immich-postgresql-longhorn"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
immichframe:
  global:
    fullnameOverride: immichframe
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/immichframe/immichframe
            tag: v1.0.33.0
            pullPolicy: IfNotPresent
          env:
            TZ: "Europe/Berlin"
            ImmichServerUrl: "https://immich.cluster.diluz.io"
            ApiKey: "TODOCHANGEME"
            AuthenticationSecret: "TODOCHANGEME"
            Albums: "fab42b63-cdc9-462c-80df-40fdd80e2a4f,1ab57e8f-39bb-4eda-84b8-bb9781e73274"
            ShowMemories: false
            ShowFavorites: false
            ImageZoom: false
            Interval: 45
            ShowClock: true
            ShowProgressBar: true
            ShowPhotoDate: true
            ShowImageDesc: true
            ShowPeopleDesc: true
            ShowAlbumName: true
            ShowImageLocation: true

  service:
    main:
      controller: main
      ports:
        http:
          port: 8080

  ingress:
    main:
      enabled: true
      hosts:
        - host: immichframe.cluster.diluz.io
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
