services:
  traefik:
    image: traefik:v3
    container_name: traefik
    restart: always
    network_mode: host
    command:
      - "--log.level=DEBUG"
      # Providers
      - "--providers.docker=true"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"

      # Entry Points & Auto-Redirect
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.priority=10"

      # ACME / Let's Encrypt
      - "--certificatesresolvers.production.acme.email=dnd-server@diluz.io"
      #- "--certificatesresolvers.production.acme.storage=/ssl-certs/acme-production.json"
      - "--certificatesresolvers.production.acme.storage=/ssl-certs/acme-staging.json"
      - "--certificatesresolvers.production.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.production.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.production.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ssl-certs:/ssl-certs
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  ssl-certs:
