---
apiVersion: v2
name: matrix-synapse
description: Matrix reference homeserver
icon: https://matrix.org/images/matrix-logo.svg
appVersion: 1.98.0

type: application
version: 3.7.14
maintainers:
  - name: sebastian
    email: sebastian@diluz.io

dependencies:
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.17.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
