{{- if .Values.immich.immich.persistence.external.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-external
spec:
  accessModes:
    - {{ .Values.immich.immich.persistence.external.accessMode | quote }}
  {{- if .Values.immich.immich.persistence.external.storageClass }}
  storageClassName: {{ .Values.immich.immich.persistence.external.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.immich.immich.persistence.external.size | quote }}
  {{- end }}
