apiVersion: v1
kind: Secret
metadata:
  name: attic-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64: {{ .Values.secrets.serverToken | quote }}
